enum AntViewDisplayType {
    CENTER_PICKING,
    FOOD_PICKING,
    BORDERS_PICKING,
    DATA_SUBMITTING,
    LABYRINTH_CLEANING,
    LABYRINTH_GENERATING,
    LABYRINTH_STOP_DISPLAYING,
}

export default AntViewDisplayType
